Simulcast info
jellyfish-dev/ts-client-sdk pull request #21
Opened 2023-10-24 08:45 UTC by kamil-stasiak

2023-10-24 12:48 UTC, szebniok requested changes

2023-10-24 12:48 UTC, szebniok commented on examples/simple-app/src/main.ts
> +  console.log({ name: "trackReady", ctx });
Maybe we could join them into a single console.log call

2023-10-24 12:48 UTC, szebniok commented on examples/simple-app/src/main.ts
> +  const videoWrapper = videoPlayerTemplate.content.cloneNode(true);
```suggestion
  const videoPlayerTemplate = document.querySelector<HTMLTemplateElement>("#remote-peer-template-video")!;

  const videoWrapper = <DocumentFragment>videoPlayerTemplate.content.cloneNode(true);
```

All subsequent `querySelector` calls will require non-null assertions. I think that it's still worth it, as the `videoWrapper` is effectively typed as `any` right now.

2023-10-24 12:48 UTC, szebniok commented on examples/simple-app/src/main.ts
> +  simulcastContainer.innerHTML = (ctx?.simulcastConfig?.enabled || false).toString();
```suggestion
  simulcastContainer.innerHTML = (ctx?.simulcastConfig?.enabled ?? false).toString();
```
I think that it is a much cleaner in this case, as we are dealing with a boolean value.

2023-10-24 12:48 UTC, szebniok commented on examples/simple-app/src/main.ts
> +  tracksContainer.remove();
```suggestion
  tracksContainer?.remove();
```

2023-10-24 12:48 UTC, szebniok commented on examples/simple-app/src/main.ts
> +const setUpSimulcastCheckbox = (element: HTMLDivElement, trackId: string, encoding: "l" | "m" | "h") => {
```suggestion
const setupSimulcastCheckbox = (element: HTMLDivElement, trackId: string, encoding: "l" | "m" | "h") => {
```
The `setup` word is already used in this project, so i think it should be preffered here

2023-10-30 13:02 UTC, incubo4u approved these changes

2023-10-31 10:40 UTC, merged